### ISSUE TITLE
Global home currency

### ISSUE THREAD

**Issue by scionaltera** [scionaltera/arbitrader#301]
The current implementation assumes USD is your "default" fiat currency, and uses `convertExchangePair()` all over the place to make a conversion if the _exchange_ is configured to have a different `homeCurrency`. It would be a really helpful refactor to be able to set a currency at the top level of the configuration rather than in every exchange. For example:

```
trading:
  entrySpread: 0.008
  exitTarget: 0.0050
  fixedExposure: 30
  fiatCurrency: EUR # use EUR instead of USD as the default fiat currency
  tradeTimeout: 24

  exchanges:
```

Without this, non-US users are stuck setting `homeCurrency` for every single exchange. I would suggest naming it something other than `homeCurrency` so that the two settings don't get confused with one another during conversations.
